Repository xmake-io/xmake, pull requests merged in 2023-02, with the labels that each got.

#3332 add custom http headers when downloading packages
  CHANGELOG.md
  xmake/core/package/package.lua
  xmake/core/project/policy.lua
  xmake/modules/net/http/download.lua
  xmake/modules/private/action/require/impl/actions/download.lua
  xmake/modules/private/action/require/impl/actions/download_resources.lua
  xmake/modules/private/action/require/impl/actions/patch_sources.lua
Labels: feature request

#3334 Improve package rules loader
  xmake/core/project/package.lua
Labels: improvement

#3344 Improve to configure options and build directory
  tests/actions/config/.gitignore
  tests/actions/config/test.lua
  xmake/actions/build/main.lua
  xmake/actions/config/configheader.lua
  xmake/actions/config/main.lua
  xmake/actions/config/xmake.lua
  xmake/actions/uninstall/main.lua
  xmake/core/main.lua
  xmake/core/project/config.lua
Labels: improvement, new feature
