Repository xmake-io/xmake, pull requests merged in 2023-09, with the labels that each got.

#4159 improve to rebuild target #4154
  xmake/actions/build/build.lua
  xmake/actions/build/kinds/binary.lua
  xmake/actions/build/kinds/object.lua
  xmake/actions/build/kinds/shared.lua
  xmake/actions/build/kinds/static.lua
  xmake/actions/build/xmake.lua
  xmake/actions/config/configfiles.lua
  xmake/core/project/target.lua
  xmake/modules/core/project/depend.lua
  xmake/modules/private/action/build/object.lua
  xmake/modules/private/utils/batchcmds.lua
  xmake/rules/c++/modules/modules_support/clang.lua
  xmake/rules/c++/modules/modules_support/gcc.lua
  xmake/rules/c++/modules/modules_support/msvc.lua
  xmake/rules/c++/unity_build/unity_build.lua
  xmake/rules/c51/xmake.lua
  xmake/rules/cuda/devlink/devlink.lua
  xmake/rules/platform/linux/driver/driver_modules.lua
  xmake/rules/protobuf/module_parser.lua
  xmake/rules/protobuf/proto.lua
  xmake/rules/qt/deploy/android.lua
  xmake/rules/qt/deploy/macosx.lua
  xmake/rules/utils/merge_archive/xmake.lua
  xmake/rules/utils/merge_object/xmake.lua
  xmake/rules/utils/symbols/export_all/export_all.lua
  xmake/rules/utils/symbols/extract/xmake.lua
  xmake/rules/verilator/verilator.lua
  xmake/rules/wdk/inf/xmake.lua
  xmake/rules/wdk/man/xmake.lua
  xmake/rules/wdk/mc/xmake.lua
  xmake/rules/wdk/mof/xmake.lua
  xmake/rules/wdk/sign/xmake.lua
  xmake/rules/wdk/tracewpp/xmake.lua
  xmake/rules/xcode/application/build.lua
  xmake/rules/xcode/bundle/xmake.lua
  xmake/rules/xcode/framework/xmake.lua
  xmake/rules/xcode/info_plist/xmake.lua
  xmake/rules/xcode/storyboard/xmake.lua
  xmake/rules/xcode/xcassets/xmake.lua
Labels: improvement

#4200 Support to remote debug xmake source code
  CHANGELOG.md
  xmake/actions/service/xmake.lua
  xmake/modules/private/service/message.lua
  xmake/modules/private/service/remote_build/client.lua
  xmake/modules/private/service/remote_build/server_session.lua
  xmake/plugins/lua/main.lua
Labels: feature request

#4199 Add C++ module for `xmake project`
  xmake/rules/c++/modules/modules_support/clang.lua
  xmake/rules/c++/modules/modules_support/gcc.lua
  xmake/rules/c++/modules/modules_support/msvc.lua
Labels: improvement, generator

#4250 Improve link mechanism and order
  CHANGELOG.md
  tests/modules/graph/test.lua
  tests/projects/c++/linkorders/src/foo.cpp
  tests/projects/c++/linkorders/src/foo.h
  tests/projects/c++/linkorders/src/main.cpp
  tests/projects/c++/linkorders/test.lua
  tests/projects/c++/linkorders/xmake.lua
  xmake/core/base/graph.lua
  xmake/core/base/interpreter.lua
  xmake/core/base/scopeinfo.lua
  xmake/core/language/language.lua
  xmake/core/sandbox/modules/import/core/base/graph.lua
  xmake/core/tool/builder.lua
  xmake/languages/asm/load.lua
  xmake/languages/c++/load.lua
  xmake/languages/c++/xmake.lua
  xmake/languages/dlang/load.lua
  xmake/languages/dlang/xmake.lua
  xmake/languages/objc++/load.lua
  xmake/languages/objc++/xmake.lua
  xmake/modules/core/tools/gcc.lua
Labels: improvement
