Repository xmake-io/xmake, pull requests merged in 2023-11, with the labels that each got.

#4343 Improve `xmake test` to support for building test stub code
  tests/actions/test/src/compile_1.cpp
  tests/actions/test/src/compile_2.cpp
  tests/actions/test/tests/stub_1.cpp
  tests/actions/test/tests/stub_2.cpp
  tests/actions/test/tests/stub_n1.cpp
  tests/actions/test/tests/stub_n2.cpp
  tests/actions/test/xmake.lua
  xmake/actions/test/main.lua
Labels: feature request

#4349 feat: add check_sizeof
  xmake/core/project/option.lua
  xmake/includes/check/check_sizeof.lua
  xmake/includes/check/xmake.lua
  xmake/modules/lib/detect/check_cxsnippets.lua
Labels: feature request

#4352 Add target:check_sizeof
  tests/apis/check_xxx/xmake.lua
  xmake/core/project/option.lua
  xmake/core/project/target.lua
  xmake/includes/check/check_sizeof.lua
  xmake/modules/lib/detect/check_cxsnippets.lua
  xmake/modules/lib/detect/check_sizeof.lua
Labels: feature request

#4386 Split proto compilation into two parts
  xmake/rules/protobuf/module_parser.lua
  xmake/rules/protobuf/proto.lua
  xmake/rules/protobuf/xmake.lua
Labels: improvement

#4446 Fix `asn1c` rule
  xmake/rules/asn1c/xmake.lua
Labels: bug, improvement
